config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'lists#index'

  resources :lists, only: [:show, :new, :create, :edit, :update, :destroy]  do

    resources :bookmarks, only: [:new, :index, :create]
  end

  resources :bookmarks, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :list
  belongs_to :movie

  validates_length_of :comment, minimum: 6
  validates_uniqueness_of :movie_id, :scope => [:list_id]
end

app/models/list.rb
class List < ApplicationRecord
  has_one_attached :photo

  has_many :bookmarks
  has_many :movies, through: :bookmarks, dependent: :destroy

  validates :name, uniqueness: true
  validates :name, presence: true

end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks

  validates :title, uniqueness: true
  validates :title, presence: true
  validates :overview, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  def index
    @bookmarks = Bookmark.find(params[:list_id])
  end

  def new
    @list = List.find(params[:list_id])
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @list = List.find(params[:list_id])
    @bookmark.list = @list
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @list = @bookmark.list
    @bookmark.destroy
    redirect_to list_path(@list)

  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :find_list, only: [:edit, :update, :show, :destroy ]

  def index
    @lists = List.all
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to root_path
    else
      render :new
    end
  end


  def show
    @bookmarks = Bookmark.where(list_id: params[:id])
  end

  def destroy
    @list.destroy
    redirect_to root_path
  end

  private

  def list_params
    params.require(:list).permit(:name, :photo, :comment)
  end

  def find_list
    @list = List.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/index.html.erb
index.html.erb

app/views/bookmarks/new.html.erb
<div class="container">
<%= simple_form_for [ @list, @bookmark ] do |f| %>
  <%= f.input :comment %>
  <%= f.association :movie %>
  <%= f.button :submit, class: 'btn btn-secondary btn-block' %>
<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsWatchList</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

 <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "components/navbar"%>

      <%= yield %>
  </body>
</html>

app/views/lists/index.html.erb
<%= render "components/banner"%>
<div class="container">
<div class="row">
  <%= render "components/card"%>
</div>
</div>

app/views/lists/new.html.erb
<%= render "components/form"%>

app/views/lists/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= cl_image_path @list.photo.key, class: "d-block w-100"%>);">
  <div class="container">
    <h1 class="text-center"><%= @list.name %></h1>
  </div>
</div>


<div class="container">

<div class="cards">
<% @bookmarks.each do |bookmark| %>
<div class="card-trip">
  <%= cl_image_tag bookmark.movie.poster_url, height: 800, crop: :fill %>
  <div class="card-trip-infos">
    <div>
      <h2><%= bookmark.movie.title %></h2>
      <p class="card-text"><%= bookmark.comment %></p>
      <p class="card-text" style="color:#af2424"><i>
        <% bookmark.movie.rating.times do %>
        <i class="fas fa-star"></i>
        <% end %>
      </p>

    </div>
    <%= link_to bookmark_path(bookmark),
                method: :delete,
                data: { confirm: "Are you sure?" } do %>
              <i class="fas fa-minus-circle"></i>
    <% end %>
  </div>
</div>
  <% end %>
</div>




<%= link_to 'Add a new bookmark', new_list_bookmark_path(@list), class: "btn btn-secondary btn-block mt-3"  %>

</div>